name: base_flutter
description: "A new Flutter project."
publish_to: "none" # Prevent accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  # Core Flutter SDK and localization
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI and Design
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.3

  # State Management
  provider: ^6.1.2
  riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Navigation
  go_router: ^14.2.1

  # Internationalization
  intl: ^0.19.0

  # Networking
  dio: ^5.5.0+1
  retrofit: ^4.2.0
  pretty_dio_logger: ^1.3.1

  # Storage
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^4.2.1

  # Code Generation and Annotations
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Environment Variables
  envied: ^0.5.4+1

  # Firebase auth
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter

  # Code Linting
  flutter_lints: ^3.0.2

  # Code Generation Tools
  envied_generator: ^0.5.4+1
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.6.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  retrofit_generator: ^8.2.0

flutter_gen:
  output: lib/shared/gen
  integrations:
    flutter_svg: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
